#!/usr/bin/env python3

import os,sys
import subprocess

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
TERRAFORM_VERSION = os.environ.get('TERRAFORM_VERSION', '0.14.11')
BASE_TERRAFORM = os.environ.get('BASE_TERRAFORM', os.getcwd())

relative_path = os.path.relpath(os.getcwd(), BASE_TERRAFORM)
if relative_path.startswith('.'):
   relative_path = ''

dcommand = (
    f'docker run -it --rm '
    f'--platform linux/amd64 '
    f'-e AWS_ACCESS_KEY_ID={AWS_ACCESS_KEY_ID} '
    f'-e AWS_SECRET_ACCESS_KEY={AWS_SECRET_ACCESS_KEY} '
    f'-v ~/.ssh:/root/.ssh '
    f'-v {BASE_TERRAFORM}:/workspace '
    f'-w /workspace/{relative_path} '
    f'hashicorp/terraform:{TERRAFORM_VERSION}'
)

for i in sys.argv[1:]:
    dcommand += ' ' + i

#os.system(dcommand)
subprocess.call(dcommand, shell=True, env=os.environ)
